php:
    image: registry.cn-hangzhou.aliyuncs.com/xjcloudy/php5.6
    container_name: php
    links:
        - "redis"
    volumes:
        - ./vols/composer:/root/.composer
        - ./vols/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        - {your workspace}:/var/www/workdir
        - {your .ssh dir}:/root/.ssh
    environment:
        TZ: Asia/Shanghai
    restart: always
redis:
    image: redis:3.2
    container_name: redis
    ports:
        - "6379:6379"
    volumes:
        - ./vols/redis:/data
    environment:
        TZ: Asia/Shanghai
    restart: always
nginx:
    image: nginx:1.14-alpine
    container_name: nginx
    links:
        - php
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - {your workspace}:/var/www/workdir
        - ./vols/nginx/conf.d:/etc/nginx/conf.d
        - ./vols/nginx/includes:/etc/nginx/includes
        - ./vols/nginx/logs:/var/log/nginx
    environment:
        TZ: Asia/Shanghai
    restart: always


