FROM php:7.3-cli
RUN sed -i "s/deb.debian.org/mirrors.163.com/g" /etc/apt/sources.list && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y vim unzip git libpng-dev libfreetype6-dev libjpeg-dev python python-pip cron && \
    pip install supervisor 
RUN docker-php-ext-configure gd --enable-gd-native-ttf --with-freetype-dir=/usr/include/freetype2 --with-png-dir=/usr/include --with-jpeg-dir=/usr/includ
RUN docker-php-source extract && \
    pecl install -f mongodb redis xdebug && \
    docker-php-ext-enable redis mongodb xdebug
RUN docker-php-ext-install mysqli opcache bcmath gd pdo_mysql && \
    docker-php-source delete && \
    cp $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/conf.d/php.ini
